name: Publish into github pages

on:
  push:
    branches:
      - master

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        run: apt install nodejs npm
  build:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: npm --version
      - name: Node version
        run: node --version
