name: Publish into github pages

on:
  push:
    branches:
      - master

jobs:
  setup-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

  build:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Npm version
        run: npm --version
      - name: Node version
        run: node --version
      - name: Build app
        run: ls -a
